// ==============================================================
// Generated by Vitis HLS v2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module decompressor_kernel_discardBitStreamLL (
        ap_ready,
        bitbuffer_read,
        bits_cntr_read,
        n_bits_val,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [31:0] bitbuffer_read;
input  [5:0] bits_cntr_read;
input  [4:0] n_bits_val;
output  [31:0] ap_return_0;
output  [5:0] ap_return_1;

wire   [31:0] zext_ln73_fu_36_p1;
wire   [5:0] n_bits_val_cast_fu_32_p1;
wire   [31:0] lshr_ln73_fu_40_p2;
wire   [5:0] sub_ln74_fu_46_p2;

assign ap_ready = 1'b1;

assign lshr_ln73_fu_40_p2 = bitbuffer_read >> zext_ln73_fu_36_p1;

assign n_bits_val_cast_fu_32_p1 = n_bits_val;

assign sub_ln74_fu_46_p2 = (bits_cntr_read - n_bits_val_cast_fu_32_p1);

assign zext_ln73_fu_36_p1 = n_bits_val;

assign ap_return_0 = lshr_ln73_fu_40_p2;

assign ap_return_1 = sub_ln74_fu_46_p2;

endmodule //decompressor_kernel_discardBitStreamLL
