// ==============================================================
// Generated by Vitis HLS v2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module decompressor_kernel_huffmanDecoderLL_2_0_Pipeline_VITIS_LOOP_1130_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bl8Code_address0,
        bl8Code_ce0,
        bl8Code_we0,
        bl8Code_d0,
        codeOffsets_address0,
        codeOffsets_ce0,
        codeOffsets_we0,
        codeOffsets_d0,
        codeOffsets_1_address0,
        codeOffsets_1_ce0,
        codeOffsets_1_we0,
        codeOffsets_1_d0,
        bl9Code_address0,
        bl9Code_ce0,
        bl9Code_we0,
        bl9Code_d0,
        bl7Code_address0,
        bl7Code_ce0,
        bl7Code_we0,
        bl7Code_d0,
        bl5Code_1_address0,
        bl5Code_1_ce0,
        bl5Code_1_we0,
        bl5Code_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] bl8Code_address0;
output   bl8Code_ce0;
output   bl8Code_we0;
output  [8:0] bl8Code_d0;
output  [3:0] codeOffsets_address0;
output   codeOffsets_ce0;
output   codeOffsets_we0;
output  [15:0] codeOffsets_d0;
output  [3:0] codeOffsets_1_address0;
output   codeOffsets_1_ce0;
output   codeOffsets_1_we0;
output  [15:0] codeOffsets_1_d0;
output  [7:0] bl9Code_address0;
output   bl9Code_ce0;
output   bl9Code_we0;
output  [8:0] bl9Code_d0;
output  [6:0] bl7Code_address0;
output   bl7Code_ce0;
output   bl7Code_we0;
output  [8:0] bl7Code_d0;
output  [4:0] bl5Code_1_address0;
output   bl5Code_1_ce0;
output   bl5Code_1_we0;
output  [8:0] bl5Code_1_d0;

reg ap_idle;
reg[7:0] bl8Code_address0;
reg bl8Code_ce0;
reg bl8Code_we0;
reg[3:0] codeOffsets_address0;
reg codeOffsets_ce0;
reg codeOffsets_we0;
reg[15:0] codeOffsets_d0;
reg[3:0] codeOffsets_1_address0;
reg codeOffsets_1_ce0;
reg codeOffsets_1_we0;
reg[15:0] codeOffsets_1_d0;
reg bl9Code_ce0;
reg bl9Code_we0;
reg bl7Code_ce0;
reg bl7Code_we0;
reg bl5Code_1_ce0;
reg bl5Code_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1130_fu_308_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1130_fu_320_p1;
wire   [8:0] i_3_load_fu_301_p1;
wire   [0:0] icmp_ln1145_fu_327_p2;
wire   [0:0] icmp_ln1151_fu_343_p2;
wire   [63:0] zext_ln1158_fu_370_p1;
wire   [0:0] icmp_ln1154_fu_349_p2;
wire   [0:0] tmp_2_fu_355_p3;
wire   [63:0] zext_ln1164_fu_392_p1;
wire   [0:0] icmp_ln1160_fu_386_p2;
wire   [63:0] zext_ln1161_fu_405_p1;
wire   [63:0] zext_ln1155_fu_421_p1;
reg   [8:0] i_fu_92;
wire   [8:0] add_ln1130_fu_314_p2;
wire    ap_block_pp0_stage0_11001;
wire    ap_loop_init;
reg   [14:0] bit7_fu_96;
wire   [14:0] bit7_1_fu_410_p2;
reg   [14:0] bit9_fu_100;
wire   [14:0] bit9_1_fu_375_p2;
reg   [14:0] bit8_fu_104;
wire   [14:0] grp_fu_275_p2;
wire   [3:0] tmp_fu_333_p4;
wire   [7:0] trunc_ln1158_fu_366_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_336;
reg    ap_condition_341;
reg    ap_condition_150;
reg    ap_condition_170;
reg    ap_condition_90;
reg    ap_condition_353;
reg    ap_condition_93;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_92 = 9'd0;
#0 bit7_fu_96 = 15'd0;
#0 bit9_fu_100 = 15'd0;
#0 bit8_fu_104 = 15'd0;
#0 ap_done_reg = 1'b0;
end

decompressor_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bit7_fu_96 <= 15'd0;
        end else if ((1'b1 == ap_condition_336)) begin
            bit7_fu_96 <= bit7_1_fu_410_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        bit8_fu_104 <= 15'd48;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((((((icmp_ln1130_fu_308_p2 == 1'd0) & (icmp_ln1154_fu_349_p2 == 1'd1)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd1))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd8))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd7))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd6))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd4)))) | (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1160_fu_386_p2 == 1'd0) & (tmp_2_fu_355_p3 == 1'd1) & (icmp_ln1154_fu_349_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd0)))) begin
        bit8_fu_104 <= grp_fu_275_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bit9_fu_100 <= 15'd400;
        end else if ((1'b1 == ap_condition_341)) begin
            bit9_fu_100 <= bit9_1_fu_375_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_92 <= 9'd0;
        end else if (((icmp_ln1130_fu_308_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_92 <= add_ln1130_fu_314_p2;
        end
    end
end

always @ (*) begin
    if (((icmp_ln1130_fu_308_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bl5Code_1_ce0 = 1'b1;
    end else begin
        bl5Code_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1151_fu_343_p2 == 1'd1))) begin
        bl5Code_1_we0 = 1'b1;
    end else begin
        bl5Code_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bl7Code_ce0 = 1'b1;
    end else begin
        bl7Code_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1160_fu_386_p2 == 1'd1) & (tmp_2_fu_355_p3 == 1'd1) & (icmp_ln1154_fu_349_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd0))) begin
        bl7Code_we0 = 1'b1;
    end else begin
        bl7Code_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_90)) begin
        if ((1'b1 == ap_condition_170)) begin
            bl8Code_address0 = zext_ln1155_fu_421_p1;
        end else if ((1'b1 == ap_condition_150)) begin
            bl8Code_address0 = zext_ln1164_fu_392_p1;
        end else begin
            bl8Code_address0 = 'bx;
        end
    end else begin
        bl8Code_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((((((icmp_ln1130_fu_308_p2 == 1'd0) & (icmp_ln1154_fu_349_p2 == 1'd1)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd1))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd8))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd7))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd6))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd4)))) | (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1160_fu_386_p2 == 1'd0) & (tmp_2_fu_355_p3 == 1'd1) & (icmp_ln1154_fu_349_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd0)))) begin
        bl8Code_ce0 = 1'b1;
    end else begin
        bl8Code_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((((((icmp_ln1130_fu_308_p2 == 1'd0) & (icmp_ln1154_fu_349_p2 == 1'd1)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd1))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd8))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd7))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd6))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd4)))) | (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1160_fu_386_p2 == 1'd0) & (tmp_2_fu_355_p3 == 1'd1) & (icmp_ln1154_fu_349_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd0)))) begin
        bl8Code_we0 = 1'b1;
    end else begin
        bl8Code_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bl9Code_ce0 = 1'b1;
    end else begin
        bl9Code_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_2_fu_355_p3 == 1'd0) & (icmp_ln1154_fu_349_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd0))) begin
        bl9Code_we0 = 1'b1;
    end else begin
        bl9Code_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_93)) begin
        if ((1'b1 == ap_condition_353)) begin
            codeOffsets_1_address0 = zext_ln1130_fu_320_p1;
        end else if ((i_3_load_fu_301_p1 == 9'd4)) begin
            codeOffsets_1_address0 = 64'd4;
        end else if ((i_3_load_fu_301_p1 == 9'd6)) begin
            codeOffsets_1_address0 = 64'd6;
        end else if ((i_3_load_fu_301_p1 == 9'd7)) begin
            codeOffsets_1_address0 = 64'd7;
        end else if ((i_3_load_fu_301_p1 == 9'd8)) begin
            codeOffsets_1_address0 = 64'd8;
        end else begin
            codeOffsets_1_address0 = 'bx;
        end
    end else begin
        codeOffsets_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd8)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd7)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd6)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd4)) | (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1145_fu_327_p2 == 1'd1)))) begin
        codeOffsets_1_ce0 = 1'b1;
    end else begin
        codeOffsets_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd4))) begin
        codeOffsets_1_d0 = 16'd0;
    end else if ((((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd8)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd7)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd6)) | (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1145_fu_327_p2 == 1'd1)))) begin
        codeOffsets_1_d0 = 16'd65535;
    end else begin
        codeOffsets_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd8)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd7)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd6)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd4)) | (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1145_fu_327_p2 == 1'd1)))) begin
        codeOffsets_1_we0 = 1'b1;
    end else begin
        codeOffsets_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_93)) begin
        if ((1'b1 == ap_condition_353)) begin
            codeOffsets_address0 = zext_ln1130_fu_320_p1;
        end else if ((i_3_load_fu_301_p1 == 9'd4)) begin
            codeOffsets_address0 = 64'd4;
        end else if ((i_3_load_fu_301_p1 == 9'd6)) begin
            codeOffsets_address0 = 64'd6;
        end else if ((i_3_load_fu_301_p1 == 9'd7)) begin
            codeOffsets_address0 = 64'd7;
        end else if ((i_3_load_fu_301_p1 == 9'd8)) begin
            codeOffsets_address0 = 64'd8;
        end else begin
            codeOffsets_address0 = 'bx;
        end
    end else begin
        codeOffsets_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd8)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd7)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd6)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd4)) | (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1145_fu_327_p2 == 1'd1)))) begin
        codeOffsets_ce0 = 1'b1;
    end else begin
        codeOffsets_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd4)) | (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1145_fu_327_p2 == 1'd1)))) begin
        codeOffsets_d0 = 16'd65535;
    end else if (((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd6))) begin
        codeOffsets_d0 = 16'd0;
    end else if (((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd7))) begin
        codeOffsets_d0 = 16'd48;
    end else if (((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd8))) begin
        codeOffsets_d0 = 16'd400;
    end else begin
        codeOffsets_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd8)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd7)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd6)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_3_load_fu_301_p1 == 9'd4)) | (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1145_fu_327_p2 == 1'd1)))) begin
        codeOffsets_we0 = 1'b1;
    end else begin
        codeOffsets_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1130_fu_314_p2 = (i_fu_92 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_150 = (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (icmp_ln1160_fu_386_p2 == 1'd0) & (tmp_2_fu_355_p3 == 1'd1) & (icmp_ln1154_fu_349_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_170 = (((((((icmp_ln1130_fu_308_p2 == 1'd0) & (icmp_ln1154_fu_349_p2 == 1'd1)) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd1))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd8))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd7))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd6))) | ((icmp_ln1130_fu_308_p2 == 1'd0) & (i_3_load_fu_301_p1 == 9'd4)));
end

always @ (*) begin
    ap_condition_336 = (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1160_fu_386_p2 == 1'd1) & (tmp_2_fu_355_p3 == 1'd1) & (icmp_ln1154_fu_349_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_341 = (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1130_fu_308_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_2_fu_355_p3 == 1'd0) & (icmp_ln1154_fu_349_p2 == 1'd0) & (icmp_ln1145_fu_327_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_353 = (~(i_3_load_fu_301_p1 == 9'd8) & ~(i_3_load_fu_301_p1 == 9'd7) & ~(i_3_load_fu_301_p1 == 9'd6) & ~(i_3_load_fu_301_p1 == 9'd4) & (icmp_ln1145_fu_327_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_90 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_93 = ((icmp_ln1130_fu_308_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign bit7_1_fu_410_p2 = (bit7_fu_96 + 15'd1);

assign bit9_1_fu_375_p2 = (bit9_fu_100 + 15'd1);

assign bl5Code_1_address0 = zext_ln1130_fu_320_p1;

assign bl5Code_1_d0 = i_fu_92;

assign bl7Code_address0 = zext_ln1161_fu_405_p1;

assign bl7Code_d0 = i_fu_92;

assign bl8Code_d0 = i_fu_92;

assign bl9Code_address0 = zext_ln1158_fu_370_p1;

assign bl9Code_d0 = i_fu_92;

assign grp_fu_275_p2 = (bit8_fu_104 + 15'd1);

assign i_3_load_fu_301_p1 = i_fu_92;

assign icmp_ln1130_fu_308_p2 = ((i_fu_92 == 9'd288) ? 1'b1 : 1'b0);

assign icmp_ln1145_fu_327_p2 = ((i_fu_92 < 9'd15) ? 1'b1 : 1'b0);

assign icmp_ln1151_fu_343_p2 = ((tmp_fu_333_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln1154_fu_349_p2 = ((i_fu_92 < 9'd144) ? 1'b1 : 1'b0);

assign icmp_ln1160_fu_386_p2 = ((i_fu_92 < 9'd280) ? 1'b1 : 1'b0);

assign tmp_2_fu_355_p3 = i_fu_92[32'd8];

assign tmp_fu_333_p4 = {{i_fu_92[8:5]}};

assign trunc_ln1158_fu_366_p1 = bit9_fu_100[7:0];

assign zext_ln1130_fu_320_p1 = i_fu_92;

assign zext_ln1155_fu_421_p1 = bit8_fu_104;

assign zext_ln1158_fu_370_p1 = trunc_ln1158_fu_366_p1;

assign zext_ln1161_fu_405_p1 = bit7_fu_96;

assign zext_ln1164_fu_392_p1 = bit8_fu_104;

endmodule //decompressor_kernel_huffmanDecoderLL_2_0_Pipeline_VITIS_LOOP_1130_3
