// ==============================================================
// Generated by Vitis HLS v2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="decompressor_kernel_decompressor_kernel,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.259810,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3484,HLS_SYN_LUT=13241,HLS_VERSION=2022_2}" *)

module decompressor_kernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_input,
        out_stream_din,
        out_stream_full_n,
        out_stream_write,
        out_eos_din,
        out_eos_full_n,
        out_eos_write
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1023:0] m_axi_input;
output  [31:0] out_stream_din;
input   out_stream_full_n;
output   out_stream_write;
output  [0:0] out_eos_din;
input   out_eos_full_n;
output   out_eos_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_stream_write;
reg[0:0] out_eos_din;
reg out_eos_write;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    out_eos_blk_n;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln94_fu_260_p2;
wire   [15:0] trunc_ln42_1_fu_237_p1;
reg   [15:0] trunc_ln42_1_reg_309;
wire    ap_CS_fsm_state2;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_start;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_done;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_idle;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_ready;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_huffman_input_stream_read;
wire    grp_huffmanDecoderLL_2_0_s_fu_147_ap_start;
wire    grp_huffmanDecoderLL_2_0_s_fu_147_ap_done;
wire    grp_huffmanDecoderLL_2_0_s_fu_147_ap_idle;
wire    grp_huffmanDecoderLL_2_0_s_fu_147_ap_ready;
wire    grp_huffmanDecoderLL_2_0_s_fu_147_huffman_input_stream_read;
wire    grp_huffmanDecoderLL_2_0_s_fu_147_huffman_eos_stream_read;
wire   [15:0] grp_huffmanDecoderLL_2_0_s_fu_147_lz77_output_stream_din;
wire    grp_huffmanDecoderLL_2_0_s_fu_147_lz77_output_stream_write;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_start;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_done;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_idle;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_ready;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_lz77_output_stream_read;
wire   [31:0] grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_out_stream_din;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_out_stream_write;
wire   [31:0] grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_decompressed_count_out;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_decompressed_count_out_ap_vld;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_start;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_done;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_idle;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_ready;
wire    grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_lz77_output_stream_read;
reg    grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_start_reg;
wire    huffman_eos_stream_full_n;
reg    huffman_eos_stream_write;
wire   [0:0] icmp_ln35_fu_186_p2;
reg    ap_block_state2_ignore_call6;
wire   [15:0] huffman_input_stream_dout;
wire    huffman_input_stream_empty_n;
reg    huffman_input_stream_read;
wire    ap_CS_fsm_state3;
reg    grp_huffmanDecoderLL_2_0_s_fu_147_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [0:0] huffman_eos_stream_dout;
wire    huffman_eos_stream_empty_n;
reg    huffman_eos_stream_read;
wire    lz77_output_stream_full_n;
reg    lz77_output_stream_write;
reg    grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_start_reg;
wire    ap_CS_fsm_state7;
wire   [15:0] lz77_output_stream_dout;
wire    lz77_output_stream_empty_n;
reg    lz77_output_stream_read;
wire    ap_CS_fsm_state8;
reg    grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg   [6:0] j_fu_90;
wire   [6:0] j_1_fu_241_p2;
reg    ap_block_state2;
reg   [11:0] indvar_flatten_fu_94;
wire   [11:0] add_ln35_fu_192_p2;
wire    huffman_input_stream_full_n;
reg    huffman_input_stream_write;
wire    ap_CS_fsm_state4;
reg    ap_block_state12;
wire   [0:0] icmp_ln37_fu_201_p2;
wire   [6:0] select_ln35_fu_207_p3;
wire   [5:0] trunc_ln42_fu_215_p1;
wire   [9:0] shl_ln1_fu_219_p3;
wire   [1023:0] zext_ln42_fu_227_p1;
wire   [1023:0] lshr_ln42_fu_231_p2;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_start_reg = 1'b0;
#0 grp_huffmanDecoderLL_2_0_s_fu_147_ap_start_reg = 1'b0;
#0 grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_start_reg = 1'b0;
#0 grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_start_reg = 1'b0;
#0 j_fu_90 = 7'd0;
#0 indvar_flatten_fu_94 = 12'd0;
end

decompressor_kernel_decompressor_kernel_Pipeline_VITIS_LOOP_39_3 grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_start),
    .ap_done(grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_done),
    .ap_idle(grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_idle),
    .ap_ready(grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_ready),
    .huffman_input_stream_dout(huffman_input_stream_dout),
    .huffman_input_stream_empty_n(huffman_input_stream_empty_n),
    .huffman_input_stream_read(grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_huffman_input_stream_read)
);

decompressor_kernel_huffmanDecoderLL_2_0_s grp_huffmanDecoderLL_2_0_s_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_huffmanDecoderLL_2_0_s_fu_147_ap_start),
    .ap_done(grp_huffmanDecoderLL_2_0_s_fu_147_ap_done),
    .ap_idle(grp_huffmanDecoderLL_2_0_s_fu_147_ap_idle),
    .ap_ready(grp_huffmanDecoderLL_2_0_s_fu_147_ap_ready),
    .huffman_input_stream_dout(huffman_input_stream_dout),
    .huffman_input_stream_empty_n(huffman_input_stream_empty_n),
    .huffman_input_stream_read(grp_huffmanDecoderLL_2_0_s_fu_147_huffman_input_stream_read),
    .huffman_eos_stream_dout(huffman_eos_stream_dout),
    .huffman_eos_stream_empty_n(huffman_eos_stream_empty_n),
    .huffman_eos_stream_read(grp_huffmanDecoderLL_2_0_s_fu_147_huffman_eos_stream_read),
    .lz77_output_stream_din(grp_huffmanDecoderLL_2_0_s_fu_147_lz77_output_stream_din),
    .lz77_output_stream_full_n(lz77_output_stream_full_n),
    .lz77_output_stream_write(grp_huffmanDecoderLL_2_0_s_fu_147_lz77_output_stream_write)
);

decompressor_kernel_decompressor_kernel_Pipeline_VITIS_LOOP_64_4 grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_start),
    .ap_done(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_done),
    .ap_idle(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_idle),
    .ap_ready(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_ready),
    .lz77_output_stream_dout(lz77_output_stream_dout),
    .lz77_output_stream_empty_n(lz77_output_stream_empty_n),
    .lz77_output_stream_read(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_lz77_output_stream_read),
    .out_stream_din(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_out_stream_din),
    .out_stream_full_n(out_stream_full_n),
    .out_stream_write(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_out_stream_write),
    .decompressed_count_out(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_decompressed_count_out),
    .decompressed_count_out_ap_vld(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_decompressed_count_out_ap_vld)
);

decompressor_kernel_decompressor_kernel_Pipeline_VITIS_LOOP_87_6 grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_start),
    .ap_done(grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_done),
    .ap_idle(grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_idle),
    .ap_ready(grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_ready),
    .lz77_output_stream_dout(lz77_output_stream_dout),
    .lz77_output_stream_empty_n(lz77_output_stream_empty_n),
    .lz77_output_stream_read(grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_lz77_output_stream_read)
);

decompressor_kernel_fifo_w16_d2_S huffman_input_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(trunc_ln42_1_reg_309),
    .if_full_n(huffman_input_stream_full_n),
    .if_write(huffman_input_stream_write),
    .if_dout(huffman_input_stream_dout),
    .if_empty_n(huffman_input_stream_empty_n),
    .if_read(huffman_input_stream_read)
);

decompressor_kernel_fifo_w1_d2_S huffman_eos_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(1'd1),
    .if_full_n(huffman_eos_stream_full_n),
    .if_write(huffman_eos_stream_write),
    .if_dout(huffman_eos_stream_dout),
    .if_empty_n(huffman_eos_stream_empty_n),
    .if_read(huffman_eos_stream_read)
);

decompressor_kernel_fifo_w16_d2_S lz77_output_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_huffmanDecoderLL_2_0_s_fu_147_lz77_output_stream_din),
    .if_full_n(lz77_output_stream_full_n),
    .if_write(lz77_output_stream_write),
    .if_dout(lz77_output_stream_dout),
    .if_empty_n(lz77_output_stream_empty_n),
    .if_read(lz77_output_stream_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_ignore_call6) & (icmp_ln35_fu_186_p2 == 1'd0))) begin
            grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_ready == 1'b1)) begin
            grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_ready == 1'b1)) begin
            grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_start_reg <= 1'b1;
        end else if ((grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_ready == 1'b1)) begin
            grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_huffmanDecoderLL_2_0_s_fu_147_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_huffmanDecoderLL_2_0_s_fu_147_ap_start_reg <= 1'b1;
        end else if ((grp_huffmanDecoderLL_2_0_s_fu_147_ap_ready == 1'b1)) begin
            grp_huffmanDecoderLL_2_0_s_fu_147_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_94 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln35_fu_186_p2 == 1'd0))) begin
        indvar_flatten_fu_94 <= add_ln35_fu_192_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_fu_90 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln35_fu_186_p2 == 1'd0))) begin
        j_fu_90 <= j_1_fu_241_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln42_1_reg_309 <= trunc_ln42_1_fu_237_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state12)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((huffman_input_stream_full_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_huffmanDecoderLL_2_0_s_fu_147_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        huffman_eos_stream_read = grp_huffmanDecoderLL_2_0_s_fu_147_huffman_eos_stream_read;
    end else begin
        huffman_eos_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln35_fu_186_p2 == 1'd1))) begin
        huffman_eos_stream_write = 1'b1;
    end else begin
        huffman_eos_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        huffman_input_stream_read = grp_huffmanDecoderLL_2_0_s_fu_147_huffman_input_stream_read;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        huffman_input_stream_read = grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_huffman_input_stream_read;
    end else begin
        huffman_input_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((huffman_input_stream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        huffman_input_stream_write = 1'b1;
    end else begin
        huffman_input_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        lz77_output_stream_read = grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_lz77_output_stream_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        lz77_output_stream_read = grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_lz77_output_stream_read;
    end else begin
        lz77_output_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        lz77_output_stream_write = grp_huffmanDecoderLL_2_0_s_fu_147_lz77_output_stream_write;
    end else begin
        lz77_output_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln94_fu_260_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12)) | ((icmp_ln94_fu_260_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12)))) begin
        out_eos_blk_n = out_eos_full_n;
    end else begin
        out_eos_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12))) begin
        if ((icmp_ln94_fu_260_p2 == 1'd1)) begin
            out_eos_din = 1'd1;
        end else if ((icmp_ln94_fu_260_p2 == 1'd0)) begin
            out_eos_din = 1'd0;
        end else begin
            out_eos_din = 'bx;
        end
    end else begin
        out_eos_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln94_fu_260_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12)) | ((icmp_ln94_fu_260_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12)))) begin
        out_eos_write = 1'b1;
    end else begin
        out_eos_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out_stream_write = grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_out_stream_write;
    end else begin
        out_stream_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln35_fu_186_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln35_fu_186_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((huffman_input_stream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_huffmanDecoderLL_2_0_s_fu_147_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (1'b0 == ap_block_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_fu_192_p2 = (indvar_flatten_fu_94 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state12 = (((icmp_ln94_fu_260_p2 == 1'd0) & (out_eos_full_n == 1'b0)) | ((icmp_ln94_fu_260_p2 == 1'd1) & (out_eos_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln35_fu_186_p2 == 1'd1) & (huffman_eos_stream_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call6 = ((icmp_ln35_fu_186_p2 == 1'd1) & (huffman_eos_stream_full_n == 1'b0));
end

assign grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_start = grp_decompressor_kernel_Pipeline_VITIS_LOOP_39_3_fu_142_ap_start_reg;

assign grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_start = grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_ap_start_reg;

assign grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_start = grp_decompressor_kernel_Pipeline_VITIS_LOOP_87_6_fu_168_ap_start_reg;

assign grp_huffmanDecoderLL_2_0_s_fu_147_ap_start = grp_huffmanDecoderLL_2_0_s_fu_147_ap_start_reg;

assign icmp_ln35_fu_186_p2 = ((indvar_flatten_fu_94 == 12'd2048) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_201_p2 = ((j_fu_90 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_260_p2 = (($signed(grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_decompressed_count_out) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign j_1_fu_241_p2 = (select_ln35_fu_207_p3 + 7'd1);

assign lshr_ln42_fu_231_p2 = m_axi_input >> zext_ln42_fu_227_p1;

assign out_stream_din = grp_decompressor_kernel_Pipeline_VITIS_LOOP_64_4_fu_160_out_stream_din;

assign select_ln35_fu_207_p3 = ((icmp_ln37_fu_201_p2[0:0] == 1'b1) ? 7'd0 : j_fu_90);

assign shl_ln1_fu_219_p3 = {{trunc_ln42_fu_215_p1}, {4'd0}};

assign trunc_ln42_1_fu_237_p1 = lshr_ln42_fu_231_p2[15:0];

assign trunc_ln42_fu_215_p1 = select_ln35_fu_207_p3[5:0];

assign zext_ln42_fu_227_p1 = shl_ln1_fu_219_p3;

endmodule //decompressor_kernel
