#ifndef __NN2FPGA_NETWORK_PARAMS_H__
#define __NN2FPGA_NETWORK_PARAMS_H__

#include "ap_int.h"
#include "hls_stream.h"
#include "hls_vector.h"
#include "stdint.h"
#include "ap_axi_sdata.h"

typedef uint8_t t_weights_st;
typedef ap_axiu<8, 0, 0, 0> t_weights_stream;
const int c_inp_1 = 64;
typedef ap_uint<c_inp_1> t_in_mem;
typedef ap_axiu<c_inp_1, 0, 0, 0> t_inp_1;
typedef uint8_t t_inp_1_part;
typedef ap_fixed<8,2,AP_RND,AP_SAT> t_net_produce_0;
typedef std::array<t_net_produce_0, 1> t_net_produce_0_vector;
typedef struct {
	std::array<t_net_produce_0_vector, 1> data;
	bool last;
} t_net_produce_0_struct;
const int c_produce_stream_ich = 3;
const int c_produce_stream_iw = 32;
const int c_produce_stream_ih = 32;
const int c_node_produce_0_ich = 3;
const int c_node_produce_0_iw = 32;
const int c_node_produce_0_ih = 32;
const int c_node_produce_0_ws_out = 2;
typedef ap_fixed<32,22,AP_RND,AP_WRAP> t_net_conv_1_acc;
typedef struct {
	t_net_conv_1_acc data;
	bool last;
} t_net_conv_1_acc_struct;
typedef std::array<t_net_produce_0, 1> t_net_produce_0_reduce;
typedef std::array<t_net_produce_0_reduce, 12> t_net_produce_0_window;
typedef struct {
	t_net_produce_0_window data;
	bool last;
} t_net_produce_0_window_struct;
typedef std::array<t_net_produce_0_reduce, 1> t_net_produce_0_lb;
typedef struct {
	t_net_produce_0_lb data;
	bool last;
} t_net_produce_0_lb_struct;
typedef ap_ufixed<8,3,AP_RND,AP_SAT> t_net_conv_1;
typedef std::array<ap_ufixed<8,3,AP_RND,AP_SAT>, 4> t_net_conv_1_vector;
typedef struct {
	std::array<t_net_conv_1_vector, 1> data;
	bool last;
} t_net_conv_1_struct;
typedef ap_ufixed<8,3,AP_RND,AP_SAT> t_net_conv_1_clip;
typedef ap_ufixed<8,3,AP_RND,AP_SAT> t_net_conv_1_mask;
typedef std::nullptr_t t_net_produce_0_mod;
const int c_node_conv_1_ich = 3;
const int c_node_conv_1_och = 16;
const int c_node_conv_1_iw = 32;
const int c_node_conv_1_ih = 32;
const int c_node_conv_1_fw = 3;
const int c_node_conv_1_fh = 3;
const int c_node_conv_1_ow = 32;
const int c_node_conv_1_oh = 32;
const int c_node_conv_1_relu = 1;
const int c_node_conv_1_stride = 1;
const int c_node_conv_1_pad = 1;
const int c_node_conv_1_ops = 4;
const int c_node_conv_1_in_ops = 1;
const int c_node_conv_1_ich_ops = 1;
const int c_node_conv_1_index = 9;
const int c_node_conv_1_reuse = 2;
const int c_node_conv_1_ws = 2;
const int c_node_conv_1_ws_out = 2;
typedef ap_fixed<32,20,AP_RND,AP_WRAP> t_net_conv_2_acc;
typedef struct {
	t_net_conv_2_acc data;
	bool last;
} t_net_conv_2_acc_struct;
typedef std::array<t_net_conv_1, 1> t_net_conv_1_reduce;
typedef std::array<t_net_conv_1_reduce, 12> t_net_conv_1_window;
typedef struct {
	t_net_conv_1_window data;
	bool last;
} t_net_conv_1_window_struct;
typedef std::array<t_net_conv_1_reduce, 1> t_net_conv_1_lb;
typedef struct {
	t_net_conv_1_lb data;
	bool last;
} t_net_conv_1_lb_struct;
typedef std::array<t_net_conv_1, 1> t_net_conv_1_skip_vector;
typedef struct {
	std::array<t_net_conv_1_reduce, 1> data;
	bool last;
} t_net_conv_1_skip_struct;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_2;
typedef std::array<ap_fixed<8,3,AP_RND,AP_SAT>, 16> t_net_conv_2_vector;
typedef struct {
	std::array<t_net_conv_2_vector, 1> data;
	bool last;
} t_net_conv_2_struct;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_2_clip;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_net_conv_2_mask;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_1_mod;
const int c_node_conv_2_ich = 16;
const int c_node_conv_2_och = 16;
const int c_node_conv_2_iw = 32;
const int c_node_conv_2_ih = 32;
const int c_node_conv_2_fw = 3;
const int c_node_conv_2_fh = 3;
const int c_node_conv_2_ow = 32;
const int c_node_conv_2_oh = 32;
const int c_node_conv_2_relu = 1;
const int c_node_conv_2_stride = 1;
const int c_node_conv_2_pad = 1;
const int c_node_conv_2_ops = 16;
const int c_node_conv_2_in_ops = 4;
const int c_node_conv_2_ich_ops = 1;
const int c_node_conv_2_index = 9;
const int c_node_conv_2_reuse = 2;
const int c_node_conv_2_ws = 2;
const int c_node_conv_2_ws_out = 2;
const int c_net_conv_1_skip_add_ops = 1;
typedef ap_fixed<32,19,AP_RND,AP_WRAP> t_net_conv_4_acc;
typedef struct {
	t_net_conv_4_acc data;
	bool last;
} t_net_conv_4_acc_struct;
typedef std::array<t_net_conv_2, 1> t_net_conv_2_reduce;
typedef std::array<t_net_conv_2_reduce, 12> t_net_conv_2_window;
typedef struct {
	t_net_conv_2_window data;
	bool last;
} t_net_conv_2_window_struct;
typedef std::array<t_net_conv_2_reduce, 1> t_net_conv_2_lb;
typedef struct {
	t_net_conv_2_lb data;
	bool last;
} t_net_conv_2_lb_struct;
typedef ap_ufixed<8,3,AP_RND,AP_SAT> t_net_conv_4;
typedef std::array<ap_ufixed<8,3,AP_RND,AP_SAT>, 16> t_net_conv_4_vector;
typedef struct {
	std::array<t_net_conv_4_vector, 1> data;
	bool last;
} t_net_conv_4_struct;
typedef ap_ufixed<8,3,AP_RND,AP_SAT> t_net_conv_4_clip;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_net_conv_4_mask;
typedef std::nullptr_t t_net_conv_2_mod;
const int c_node_conv_3_ich = 16;
const int c_node_conv_3_och = 16;
const int c_node_conv_3_iw = 32;
const int c_node_conv_3_ih = 32;
const int c_node_conv_3_fw = 3;
const int c_node_conv_3_fh = 3;
const int c_node_conv_3_ow = 32;
const int c_node_conv_3_oh = 32;
const int c_node_conv_3_relu = 1;
const int c_node_conv_3_stride = 1;
const int c_node_conv_3_pad = 1;
const int c_node_conv_3_ops = 16;
const int c_node_conv_3_in_ops = 16;
const int c_node_conv_3_ich_ops = 1;
const int c_node_conv_3_index = 9;
const int c_node_conv_3_reuse = 2;
const int c_node_conv_3_ws = 2;
const int c_node_conv_3_ws_out = 2;
typedef ap_fixed<32,19,AP_RND,AP_WRAP> t_net_conv_5_acc;
typedef struct {
	t_net_conv_5_acc data;
	bool last;
} t_net_conv_5_acc_struct;
typedef std::array<t_net_conv_4, 1> t_net_conv_4_reduce;
typedef std::array<t_net_conv_4_reduce, 15> t_net_conv_4_window;
typedef struct {
	t_net_conv_4_window data;
	bool last;
} t_net_conv_4_window_struct;
typedef std::array<t_net_conv_4_reduce, 1> t_net_conv_4_lb;
typedef struct {
	t_net_conv_4_lb data;
	bool last;
} t_net_conv_4_lb_struct;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_5;
typedef std::array<ap_fixed<8,3,AP_RND,AP_SAT>, 8> t_net_conv_5_vector;
typedef struct {
	std::array<t_net_conv_5_vector, 1> data;
	bool last;
} t_net_conv_5_struct;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_5_clip;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_net_conv_5_mask;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_6;
typedef std::array<t_net_conv_6, 8> t_net_conv_6_vector;
typedef struct {
	std::array<t_net_conv_6_vector, 1> data;
	bool last;
} t_net_conv_6_struct;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_net_conv_4_mod;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_4_1x1;
typedef ap_fixed<32,17,AP_RND,AP_SAT> t_net_conv_6_acc;
typedef struct {
	t_net_conv_6_acc data;
	bool last;
} t_net_conv_6_acc_struct;
const int c_net_conv_6_add_ops = 8;
const int c_node_conv_4_ich = 16;
const int c_node_conv_4_och = 32;
const int c_node_conv_4_iw = 32;
const int c_node_conv_4_ih = 32;
const int c_node_conv_4_fw = 3;
const int c_node_conv_4_fh = 3;
const int c_node_conv_4_ow = 16;
const int c_node_conv_4_oh = 16;
const int c_node_conv_4_relu = 1;
const int c_node_conv_4_stride = 2;
const int c_node_conv_4_pad = 1;
const int c_node_conv_4_ops = 8;
const int c_node_conv_4_in_ops = 16;
const int c_node_conv_4_ich_ops = 1;
const int c_node_conv_4_index = 9;
const int c_node_conv_4_reuse = 2;
const int c_node_conv_4_ws = 2;
const int c_node_conv_4_ws_out = 2;
typedef ap_fixed<32,19,AP_RND,AP_WRAP> t_net_conv_7_acc;
typedef struct {
	t_net_conv_7_acc data;
	bool last;
} t_net_conv_7_acc_struct;
typedef std::array<t_net_conv_5, 1> t_net_conv_5_reduce;
typedef std::array<t_net_conv_5_reduce, 12> t_net_conv_5_window;
typedef struct {
	t_net_conv_5_window data;
	bool last;
} t_net_conv_5_window_struct;
typedef std::array<t_net_conv_5_reduce, 1> t_net_conv_5_lb;
typedef struct {
	t_net_conv_5_lb data;
	bool last;
} t_net_conv_5_lb_struct;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_7;
typedef std::array<ap_fixed<8,3,AP_RND,AP_SAT>, 16> t_net_conv_7_vector;
typedef struct {
	std::array<t_net_conv_7_vector, 1> data;
	bool last;
} t_net_conv_7_struct;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_7_clip;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_net_conv_7_mask;
typedef std::nullptr_t t_net_conv_5_mod;
const int c_node_conv_5_ich = 32;
const int c_node_conv_5_och = 32;
const int c_node_conv_5_iw = 16;
const int c_node_conv_5_ih = 16;
const int c_node_conv_5_fw = 3;
const int c_node_conv_5_fh = 3;
const int c_node_conv_5_ow = 16;
const int c_node_conv_5_oh = 16;
const int c_node_conv_5_relu = 1;
const int c_node_conv_5_stride = 1;
const int c_node_conv_5_pad = 1;
const int c_node_conv_5_ops = 16;
const int c_node_conv_5_in_ops = 8;
const int c_node_conv_5_ich_ops = 1;
const int c_node_conv_5_index = 9;
const int c_node_conv_5_reuse = 2;
const int c_node_conv_5_ws = 2;
const int c_node_conv_5_ws_out = 2;
typedef ap_fixed<32,18,AP_RND,AP_WRAP> t_net_conv_8_acc;
typedef struct {
	t_net_conv_8_acc data;
	bool last;
} t_net_conv_8_acc_struct;
typedef std::array<t_net_conv_7, 1> t_net_conv_7_reduce;
typedef std::array<t_net_conv_7_reduce, 15> t_net_conv_7_window;
typedef struct {
	t_net_conv_7_window data;
	bool last;
} t_net_conv_7_window_struct;
typedef std::array<t_net_conv_7_reduce, 1> t_net_conv_7_lb;
typedef struct {
	t_net_conv_7_lb data;
	bool last;
} t_net_conv_7_lb_struct;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_8;
typedef std::array<ap_fixed<8,3,AP_RND,AP_SAT>, 8> t_net_conv_8_vector;
typedef struct {
	std::array<t_net_conv_8_vector, 1> data;
	bool last;
} t_net_conv_8_struct;
typedef ap_fixed<8,3,AP_RND,AP_SAT> t_net_conv_8_clip;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_net_conv_8_mask;
typedef ap_fixed<8,2,AP_RND,AP_SAT> t_net_conv_9;
typedef std::array<t_net_conv_9, 8> t_net_conv_9_vector;
typedef struct {
	std::array<t_net_conv_9_vector, 1> data;
	bool last;
} t_net_conv_9_struct;
typedef std::nullptr_t t_net_conv_7_mod;
typedef std::nullptr_t t_net_conv_7_1x1;
typedef ap_fixed<32,19,AP_RND,AP_SAT> t_net_conv_9_acc;
typedef struct {
	t_net_conv_9_acc data;
	bool last;
} t_net_conv_9_acc_struct;
const int c_net_conv_9_add_ops = 8;
const int c_node_conv_6_ich = 32;
const int c_node_conv_6_och = 64;
const int c_node_conv_6_iw = 16;
const int c_node_conv_6_ih = 16;
const int c_node_conv_6_fw = 3;
const int c_node_conv_6_fh = 3;
const int c_node_conv_6_ow = 8;
const int c_node_conv_6_oh = 8;
const int c_node_conv_6_relu = 1;
const int c_node_conv_6_stride = 2;
const int c_node_conv_6_pad = 1;
const int c_node_conv_6_ops = 8;
const int c_node_conv_6_in_ops = 16;
const int c_node_conv_6_ich_ops = 1;
const int c_node_conv_6_index = 9;
const int c_node_conv_6_reuse = 2;
const int c_node_conv_6_ws = 2;
const int c_node_conv_6_ws_out = 2;
typedef ap_fixed<32,19,AP_RND,AP_WRAP> t_net_conv_10_acc;
typedef struct {
	t_net_conv_10_acc data;
	bool last;
} t_net_conv_10_acc_struct;
typedef std::array<t_net_conv_8, 1> t_net_conv_8_reduce;
typedef std::array<t_net_conv_8_reduce, 12> t_net_conv_8_window;
typedef struct {
	t_net_conv_8_window data;
	bool last;
} t_net_conv_8_window_struct;
typedef std::array<t_net_conv_8_reduce, 1> t_net_conv_8_lb;
typedef struct {
	t_net_conv_8_lb data;
	bool last;
} t_net_conv_8_lb_struct;
typedef ap_ufixed<8,3,AP_RND,AP_SAT> t_net_conv_10;
typedef std::array<ap_ufixed<8,3,AP_RND,AP_SAT>, 16> t_net_conv_10_vector;
typedef struct {
	std::array<t_net_conv_10_vector, 1> data;
	bool last;
} t_net_conv_10_struct;
typedef ap_ufixed<8,3,AP_RND,AP_SAT> t_net_conv_10_clip;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_net_conv_10_mask;
typedef std::nullptr_t t_net_conv_8_mod;
const int c_node_conv_7_ich = 64;
const int c_node_conv_7_och = 64;
const int c_node_conv_7_iw = 8;
const int c_node_conv_7_ih = 8;
const int c_node_conv_7_fw = 3;
const int c_node_conv_7_fh = 3;
const int c_node_conv_7_ow = 8;
const int c_node_conv_7_oh = 8;
const int c_node_conv_7_relu = 1;
const int c_node_conv_7_stride = 1;
const int c_node_conv_7_pad = 1;
const int c_node_conv_7_ops = 16;
const int c_node_conv_7_in_ops = 8;
const int c_node_conv_7_ich_ops = 1;
const int c_node_conv_7_index = 9;
const int c_node_conv_7_reuse = 2;
const int c_node_conv_7_ws = 2;
const int c_node_conv_7_ws_out = 2;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_net_pool_11;
typedef std::array<t_net_pool_11, 16> t_net_pool_11_vector;
typedef struct {
	std::array<t_net_pool_11_vector, 1> data;
	bool last;
} t_net_pool_11_struct;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_node_pool_8_acc;
const int c_node_pool_8_ich = 64;
const int c_node_pool_8_och = 64;
const int c_node_pool_8_iw = 8;
const int c_node_pool_8_ih = 8;
const int c_node_pool_8_ow = 1;
const int c_node_pool_8_oh = 1;
const int c_node_pool_8_fw = 8;
const int c_node_pool_8_fh = 8;
const int c_node_pool_8_stride = 1;
const int c_node_pool_8_pad = 0;
const int c_node_pool_8_pool = 1;
const int c_node_pool_8_ws = 2;
const int c_node_pool_8_ws_out = 1;
const int c_node_pool_8_ops = 16;
const int c_node_pool_8_in_ops = 16;
typedef ap_fixed<32,22,AP_RND,AP_WRAP> t_net_conv_12_acc;
typedef struct {
	t_net_conv_12_acc data;
	bool last;
} t_net_conv_12_acc_struct;
typedef std::array<t_net_pool_11, 16> t_net_pool_11_reduce;
typedef std::array<t_net_pool_11_reduce, 1> t_net_pool_11_window;
typedef struct {
	t_net_pool_11_window data;
	bool last;
} t_net_pool_11_window_struct;
typedef std::array<t_net_pool_11_reduce, 1> t_net_pool_11_lb;
typedef struct {
	t_net_pool_11_lb data;
	bool last;
} t_net_pool_11_lb_struct;
typedef ap_fixed<8,5,AP_RND,AP_SAT> t_net_conv_12;
typedef std::array<ap_fixed<8,5,AP_RND,AP_SAT>, 1> t_net_conv_12_vector;
typedef struct {
	std::array<t_net_conv_12_vector, 1> data;
	bool last;
} t_net_conv_12_struct;
typedef ap_fixed<8,5,AP_RND,AP_SAT> t_net_conv_12_clip;
typedef ap_fixed<8,5,AP_RND,AP_SAT> t_net_conv_12_mask;
typedef std::nullptr_t t_net_pool_11_mod;
const int c_node_conv_9_ich = 64;
const int c_node_conv_9_och = 10;
const int c_node_conv_9_iw = 1;
const int c_node_conv_9_ih = 1;
const int c_node_conv_9_fw = 1;
const int c_node_conv_9_fh = 1;
const int c_node_conv_9_ow = 1;
const int c_node_conv_9_oh = 1;
const int c_node_conv_9_relu = 0;
const int c_node_conv_9_stride = 1;
const int c_node_conv_9_pad = 0;
const int c_node_conv_9_ops = 1;
const int c_node_conv_9_in_ops = 16;
const int c_node_conv_9_ich_ops = 16;
const int c_node_conv_9_index = 1;
const int c_node_conv_9_reuse = 1;
const int c_node_conv_9_ws = 1;
const int c_node_conv_9_ws_out = 1;
typedef hls::axis<t_net_conv_12, 0, 0, 0> t_o_net_conv_12;
using t_out_mem=t_net_conv_12;
using t_o_outp1=t_o_net_conv_12;
using t_o_data=t_o_net_conv_12;
const int c_node_const_29_ws = 1;
typedef ap_fixed<8,4,AP_RND,AP_SAT> t_net_const_13_st;
typedef t_net_const_13_st t_net_const_13_init;
typedef hls::vector<ap_fixed<8,4,AP_RND,AP_SAT>, 4> t_net_const_13;
const int c_node_const_10_ich = 3;
const int c_node_const_10_och = 16;
const int c_node_const_10_ow = 32;
const int c_node_const_10_oh = 32;
const int c_net_const_13_iw = 3;
const int c_net_const_13_ih = 3;
const int c_net_const_13_ops = 4;
const int c_net_const_13_reuse = 2;
typedef ap_fixed<16,6,AP_RND,AP_SAT> t_net_const_14_st;
typedef t_net_const_14_st t_net_const_14_init;
typedef hls::vector<ap_fixed<16,6,AP_RND,AP_SAT>, 4> t_net_const_14;
const int c_node_const_11_ich = 1;
const int c_node_const_11_och = 16;
const int c_node_const_11_ow = 32;
const int c_node_const_11_oh = 32;
const int c_net_const_14_iw = 1;
const int c_net_const_14_ih = 1;
const int c_net_const_14_ops = 4;
const int c_net_const_14_reuse = 2;
typedef ap_fixed<8,1,AP_RND,AP_SAT> t_net_const_15_st;
typedef t_net_const_15_st t_net_const_15_init;
typedef hls::vector<ap_fixed<8,1,AP_RND,AP_SAT>, 16> t_net_const_15;
const int c_node_const_12_ich = 16;
const int c_node_const_12_och = 16;
const int c_node_const_12_ow = 32;
const int c_node_const_12_oh = 32;
const int c_net_const_15_iw = 3;
const int c_net_const_15_ih = 3;
const int c_net_const_15_ops = 16;
const int c_net_const_15_reuse = 2;
typedef ap_fixed<16,4,AP_RND,AP_SAT> t_net_const_16_st;
typedef t_net_const_16_st t_net_const_16_init;
typedef hls::vector<ap_fixed<16,4,AP_RND,AP_SAT>, 16> t_net_const_16;
const int c_node_const_13_ich = 1;
const int c_node_const_13_och = 16;
const int c_node_const_13_ow = 32;
const int c_node_const_13_oh = 32;
const int c_net_const_16_iw = 1;
const int c_net_const_16_ih = 1;
const int c_net_const_16_ops = 16;
const int c_net_const_16_reuse = 2;
typedef ap_fixed<8,0,AP_RND,AP_SAT> t_net_const_17_st;
typedef t_net_const_17_st t_net_const_17_init;
typedef hls::vector<ap_fixed<8,0,AP_RND,AP_SAT>, 16> t_net_const_17;
const int c_node_const_14_ich = 16;
const int c_node_const_14_och = 16;
const int c_node_const_14_ow = 32;
const int c_node_const_14_oh = 32;
const int c_net_const_17_iw = 3;
const int c_net_const_17_ih = 3;
const int c_net_const_17_ops = 16;
const int c_net_const_17_reuse = 2;
typedef ap_fixed<16,3,AP_RND,AP_SAT> t_net_const_18_st;
typedef t_net_const_18_st t_net_const_18_init;
typedef hls::vector<ap_fixed<16,3,AP_RND,AP_SAT>, 16> t_net_const_18;
const int c_node_const_15_ich = 1;
const int c_node_const_15_och = 16;
const int c_node_const_15_ow = 32;
const int c_node_const_15_oh = 32;
const int c_net_const_18_iw = 1;
const int c_net_const_18_ih = 1;
const int c_net_const_18_ops = 16;
const int c_net_const_18_reuse = 2;
typedef ap_fixed<8,0,AP_RND,AP_SAT> t_net_const_19_st;
typedef t_net_const_19_st t_net_const_19_init;
typedef hls::vector<ap_fixed<8,0,AP_RND,AP_SAT>, 8> t_net_const_19;
const int c_node_const_16_ich = 16;
const int c_node_const_16_och = 32;
const int c_node_const_16_ow = 16;
const int c_node_const_16_oh = 16;
const int c_net_const_19_iw = 3;
const int c_net_const_19_ih = 3;
const int c_net_const_19_ops = 8;
const int c_net_const_19_reuse = 2;
typedef ap_fixed<16,4,AP_RND,AP_SAT> t_net_const_20_st;
typedef t_net_const_20_st t_net_const_20_init;
typedef hls::vector<ap_fixed<16,4,AP_RND,AP_SAT>, 8> t_net_const_20;
const int c_node_const_17_ich = 1;
const int c_node_const_17_och = 32;
const int c_node_const_17_ow = 16;
const int c_node_const_17_oh = 16;
const int c_net_const_20_iw = 1;
const int c_net_const_20_ih = 1;
const int c_net_const_20_ops = 8;
const int c_net_const_20_reuse = 2;
typedef ap_fixed<8,0,AP_RND,AP_SAT> t_net_const_21_st;
typedef t_net_const_21_st t_net_const_21_init;
typedef hls::vector<ap_fixed<8,0,AP_RND,AP_SAT>, 16> t_net_const_21;
const int c_node_const_18_ich = 32;
const int c_node_const_18_och = 32;
const int c_node_const_18_ow = 16;
const int c_node_const_18_oh = 16;
const int c_net_const_21_iw = 3;
const int c_net_const_21_ih = 3;
const int c_net_const_21_ops = 16;
const int c_net_const_21_reuse = 2;
typedef ap_fixed<16,3,AP_RND,AP_SAT> t_net_const_22_st;
typedef t_net_const_22_st t_net_const_22_init;
typedef hls::vector<ap_fixed<16,3,AP_RND,AP_SAT>, 16> t_net_const_22;
const int c_node_const_19_ich = 1;
const int c_node_const_19_och = 32;
const int c_node_const_19_ow = 16;
const int c_node_const_19_oh = 16;
const int c_net_const_22_iw = 1;
const int c_net_const_22_ih = 1;
const int c_net_const_22_ops = 16;
const int c_net_const_22_reuse = 2;
typedef ap_fixed<8,0,AP_RND,AP_SAT> t_net_const_23_st;
typedef t_net_const_23_st t_net_const_23_init;
typedef hls::vector<ap_fixed<8,0,AP_RND,AP_SAT>, 8> t_net_const_23;
const int c_node_const_20_ich = 16;
const int c_node_const_20_och = 32;
const int c_node_const_20_ow = 16;
const int c_node_const_20_oh = 16;
const int c_net_const_23_iw = 1;
const int c_net_const_23_ih = 1;
const int c_net_const_23_ops = 8;
const int c_net_const_23_reuse = 2;
typedef ap_fixed<16,3,AP_RND,AP_SAT> t_net_const_24_st;
typedef t_net_const_24_st t_net_const_24_init;
typedef hls::vector<ap_fixed<16,3,AP_RND,AP_SAT>, 8> t_net_const_24;
const int c_node_const_21_ich = 1;
const int c_node_const_21_och = 32;
const int c_node_const_21_ow = 16;
const int c_node_const_21_oh = 16;
const int c_net_const_24_iw = 1;
const int c_net_const_24_ih = 1;
const int c_net_const_24_ops = 8;
const int c_net_const_24_reuse = 2;
typedef ap_fixed<8,-1,AP_RND,AP_SAT> t_net_const_25_st;
typedef t_net_const_25_st t_net_const_25_init;
typedef hls::vector<ap_fixed<8,-1,AP_RND,AP_SAT>, 8> t_net_const_25;
const int c_node_const_22_ich = 32;
const int c_node_const_22_och = 64;
const int c_node_const_22_ow = 8;
const int c_node_const_22_oh = 8;
const int c_net_const_25_iw = 3;
const int c_net_const_25_ih = 3;
const int c_net_const_25_ops = 8;
const int c_net_const_25_reuse = 2;
typedef ap_fixed<16,2,AP_RND,AP_SAT> t_net_const_26_st;
typedef t_net_const_26_st t_net_const_26_init;
typedef hls::vector<ap_fixed<16,2,AP_RND,AP_SAT>, 8> t_net_const_26;
const int c_node_const_23_ich = 1;
const int c_node_const_23_och = 64;
const int c_node_const_23_ow = 8;
const int c_node_const_23_oh = 8;
const int c_net_const_26_iw = 1;
const int c_net_const_26_ih = 1;
const int c_net_const_26_ops = 8;
const int c_net_const_26_reuse = 2;
typedef ap_fixed<8,0,AP_RND,AP_SAT> t_net_const_27_st;
typedef t_net_const_27_st t_net_const_27_init;
typedef hls::vector<ap_fixed<8,0,AP_RND,AP_SAT>, 16> t_net_const_27;
const int c_node_const_24_ich = 64;
const int c_node_const_24_och = 64;
const int c_node_const_24_ow = 8;
const int c_node_const_24_oh = 8;
const int c_net_const_27_iw = 3;
const int c_net_const_27_ih = 3;
const int c_net_const_27_ops = 16;
const int c_net_const_27_reuse = 2;
typedef ap_fixed<16,3,AP_RND,AP_SAT> t_net_const_28_st;
typedef t_net_const_28_st t_net_const_28_init;
typedef hls::vector<ap_fixed<16,3,AP_RND,AP_SAT>, 16> t_net_const_28;
const int c_node_const_25_ich = 1;
const int c_node_const_25_och = 64;
const int c_node_const_25_ow = 8;
const int c_node_const_25_oh = 8;
const int c_net_const_28_iw = 1;
const int c_net_const_28_ih = 1;
const int c_net_const_28_ops = 16;
const int c_net_const_28_reuse = 2;
typedef ap_fixed<8,0,AP_RND,AP_SAT> t_net_const_29_st;
typedef t_net_const_29_st t_net_const_29_init;
typedef hls::vector<ap_fixed<8,0,AP_RND,AP_SAT>, 8> t_net_const_29;
const int c_node_const_26_ich = 32;
const int c_node_const_26_och = 64;
const int c_node_const_26_ow = 8;
const int c_node_const_26_oh = 8;
const int c_net_const_29_iw = 1;
const int c_net_const_29_ih = 1;
const int c_net_const_29_ops = 8;
const int c_net_const_29_reuse = 2;
typedef ap_fixed<16,3,AP_RND,AP_SAT> t_net_const_30_st;
typedef t_net_const_30_st t_net_const_30_init;
typedef hls::vector<ap_fixed<16,3,AP_RND,AP_SAT>, 8> t_net_const_30;
const int c_node_const_27_ich = 1;
const int c_node_const_27_och = 64;
const int c_node_const_27_ow = 8;
const int c_node_const_27_oh = 8;
const int c_net_const_30_iw = 1;
const int c_net_const_30_ih = 1;
const int c_net_const_30_ops = 8;
const int c_net_const_30_reuse = 2;
typedef ap_fixed<8,2,AP_RND,AP_SAT> t_net_const_31_st;
typedef t_net_const_31_st t_net_const_31_init;
typedef hls::vector<ap_fixed<8,2,AP_RND,AP_SAT>, 1> t_net_const_31;
const int c_node_const_28_ich = 64;
const int c_node_const_28_och = 10;
const int c_node_const_28_ow = 1;
const int c_node_const_28_oh = 1;
const int c_net_const_31_iw = 1;
const int c_net_const_31_ih = 1;
const int c_net_const_31_ops = 1;
const int c_net_const_31_reuse = 1;
typedef ap_fixed<16,6,AP_RND,AP_SAT> t_net_const_32_st;
typedef t_net_const_32_st t_net_const_32_init;
typedef hls::vector<ap_fixed<16,6,AP_RND,AP_SAT>, 1> t_net_const_32;
const int c_node_const_29_ich = 1;
const int c_node_const_29_och = 10;
const int c_node_const_29_ow = 1;
const int c_node_const_29_oh = 1;
const int c_net_const_32_iw = 1;
const int c_net_const_32_ih = 1;
const int c_net_const_32_ops = 1;
const int c_net_const_32_reuse = 1;

#endif /*__NN3FPGA_NETWORK_PARAMS_H__ */
